### ISSUE TITLE
regmixEM.loc does not work when 'x' is a matrix

### ISSUE THREAD

**Issue by jtrecenti** [dsy109/mixtools#4]
Hi! Thanks for this awesome package!

I was trying to run `regmixEM.loc` and maybe I have misinterpreted the documentation.

Documentation shows that `x` is `An nxp matrix of predictors. See addintercept below`: [link](https://github.com/dsy109/mixtools/blob/b9e0c29d5e908006dcbd33da9f502c1116780315/man/regmixEM.loc.Rd#L19).

However, if we try to run the example with a matrix, it throws an error:

``` r
library(mixtools)
#> mixtools package, version 1.2.0, Released 2020-02-05
#> This package is based upon work supported by the National Science Foundation under Grant No. SES-0518772.
data(NOdata)

# works
res <- regmixEM.loc(NOdata$Equivalence, NOdata$NO)
#> number of overall iterations= 10

# does not work, but x is a nxp matrix, with p=1
res <- regmixEM.loc(NOdata$Equivalence, as.matrix(NOdata[,c("NO")]))
#> Error in W * X.mat: arrays de dimensão não compatível
```

<sup>Created on 2022-11-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This error occurs inside the `mixtools:::lambda` function, [this line](https://github.com/dsy109/mixtools/blob/b9e0c29d5e908006dcbd33da9f502c1116780315/R/lambda.R#L27)

The error also occurs when we try with $p>1$:

``` r
library(mixtools)
#> mixtools package, version 1.2.0, Released 2020-02-05
#> This package is based upon work supported by the National Science Foundation under Grant No. SES-0518772.
data(NOdata)


NOdata$random <- runif(nrow(NOdata))

# does not work, but x is a nxp matrix, with p=2
res <- regmixEM.loc(NOdata$Equivalence, as.matrix(NOdata[,c("NO", "random")]))
#> Error in W * X.mat: arrays de dimensão não compatível
```

<sup>Created on 2022-11-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thanks!

**Comment by dsy109** [comment]
Thank you for the feedback about ```mixtools```, @jtrecenti!

I delayed in responding because you posted this comment while I was in the middle of finalizing the newest release of ```mixtools``` ([v2.0.0](https://github.com/dsy109/mixtools/releases/tag/v2.0.0)).  I was able to fix this error.  This function was originally written about 15 years ago and was intended to be generalized for $p>2$.  However, I had not completed that generalization at the time.  ```regmixEM.loc``` and ```mixtools:::lambda``` have both been updated, where the latter uses a product kernel in the calculation when considering multiple predictors.

Below demonstrates the updated results for the example you provided:
```R
library(mixtools)
#> mixtools package, version 2.0.0, Released 2022-12-04
#> This package is based upon work supported by the National Science Foundation under Grant No. SES-0518772 
#> and the Chan Zuckerberg Initiative: Essential Open Source Software for Science (Grant No. 2020-255193).

data(NOdata)
set.seed(1)
NOdata$random <- runif(nrow(NOdata))
res <- regmixEM.loc(NOdata$Equivalence, as.matrix(NOdata[,c("NO", "random")]))
#> number of overall iterations= 20 
head(res$lambda.x);res$beta
          [,1]       [,2]
[1,] 0.9144855 0.08551452
[2,] 0.4946376 0.50536243
[3,] 0.5002606 0.49973939
[4,] 0.5525099 0.44749010
[5,] 0.5019446 0.49805544
[6,] 0.6337956 0.36620437
            comp.1      comp.2
beta.0 0.555442498  1.25621371
beta.1 0.089544846 -0.08509940
beta.2 0.007504679 -0.01127393
```

I also acknowledged you in the [NEWS](https://github.com/dsy109/mixtools/blob/master/NEWS) file for identifying this issue.

Please let me know if you encounter other issues with this function.  Thanks!

**Comment by jtrecenti** [comment]
Thank you very much! Thid solves the issue. And congratulations for the version 2.0.0!
